// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechPrimeLab.Data;

#nullable disable

namespace TechPrimeLab.Migrations
{
    [DbContext(typeof(TechPrimeDBContext))]
    partial class TechPrimeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechPrimeLab.Models.ProjectDetails", b =>
                {
                    b.Property<Guid>("project_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("project_category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("project_department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("project_division")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("project_location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("project_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("project_priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("project_reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("project_status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("project_theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("project_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("project_user_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("project_id");

                    b.ToTable("project_details");
                });

            modelBuilder.Entity("TechPrimeLab.Models.UserDetails", b =>
                {
                    b.Property<Guid>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("created_ts")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_ts")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("password_hash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("password_salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("user_id");

                    b.ToTable("user_details");
                });
#pragma warning restore 612, 618
        }
    }
}
